<?php if ($block->getCollection()->getSize()) : ?>

<div class="toolbar toolbar-products">

    <?php if (!$block->getIsBottom()): ?>

        <?php if ($block->isExpanded()): ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
        <?php endif; ?>

        <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
      
        <?php if ($block->isExpanded()): ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
        <?php endif; ?>
        

    <?php endif; ?>

    <?= $block->getPagerHtml() ?>

</div>

<?php endif; ?>