<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /* @var $block \Magento\Catalog\Block\Product\View\AbstractView */?>
<?php $_product = $block->getProduct();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$stockRegistry = $objectManager->get('Magento\CatalogInventory\Api\StockRegistryInterface');
$stockItem=$stockRegistry->getStockItem($_product->getId());
$manageStock = $stockItem->getData('manage_stock');
?>
 
<?php if ($block->displayProductStockStatus()): ?>
    <?php if ($_product->isAvailable()): ?>
		<?php if($manageStock == 0 && $stockItem->getQty() == 0): ?>
			<div class="stock available noqty" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
				<span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
			</div>
		<?php else: ?>
        <div class="stock available" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
        </div>
		<?php endif; ?>
    <?php else: ?>
        <div class="stock unavailable" title="<?= /* @escapeNotVerified */ __('Availability') ?>">
            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
