<?php
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile
?>

<div class="container">

<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

if ($category) {
$subcats = $category->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<ul style="padding:0;float:left;width:100%">
<?php
foreach ($subcats as $subcat) {
if ($subcat->getIsActive()) {

$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
$_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
$subcaturl = $subcat->getUrl();

$_imgHtml = '';

if ($_imgUrl = $_category->getImageUrl()) {

$_imgHtml = '<img src="' . $_imgUrl . '" />';
$_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');

echo '<li style="list-style-type:none;margin-right:1%;float:left">
<a href="' . $subcaturl . '" class="block-promo" title="' . $subcat->getName() . '">' . $_imgHtml . '</a>
</li>';

}
}
}
?>
</ul>

<?php } ?>


<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>

<?php if (!$_productCollection->count()): ?>

<div class="message info empty">
<div><?= __('We can\'t find products matching the selection.') ?></div>
</div>

<?php else: ?>

<?= $block->getToolbarHtml() ?>
<?= $block->getAdditionalHtml() ?>

<?php
if ($block->getMode() == 'grid') {
$viewMode = 'grid';
$imageDisplayArea = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
} else {
$viewMode = 'list';
$imageDisplayArea = 'category_page_list';
$showDescription = true;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
}

$pos = (string)$block->getPositioned(); // FIXED for PHP 8+
?>

<div class="products wrapper-custom <?= $viewMode ?> products-<?= $viewMode ?> w-[100%]">
<ol class="products list items product-items">

<?php foreach ($_productCollection as $_product): ?>

<li class="item product product-item">

<div class="product-item-info" data-container="product-<?= $viewMode ?>">

<?php
$productImage = $block->getImage($_product, $imageDisplayArea);

$position = '';

if (!empty($pos)) {
$position = ' style="left:' . $productImage->getWidth() . 'px;top:' . $productImage->getHeight() . 'px;"';
}
?>

<a href="<?= $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
<?= $productImage->toHtml() ?>
</a>

<div class="product details product-item-details">

<?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>

<strong class="product name product-item-name">

<a class="product-item-link" href="<?= $_product->getProductUrl() ?>">
<?= $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
</a>

</strong>

<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
<?= $block->getProductPrice($_product) ?>
<?= $block->getProductDetailsHtml($_product) ?>

<div class="product-item-inner">

<div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') !== false ? $position : '' ?>>

<div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') !== false ? $position : '' ?>>

<?php if ($_product->isSaleable()): ?>

<?php $postParams = $block->getAddToCartPostParams($_product); ?>

<form data-role="tocart-form"
data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
action="<?= $postParams['action'] ?>"
method="post">

<input type="hidden" name="product" value="<?= $postParams['data']['product'] ?>">

<input type="hidden"
name="<?= Action::PARAM_NAME_URL_ENCODED ?>"
value="<?= $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">

<?= $block->getBlockHtml('formkey') ?>

<button type="submit"
title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
class="action tocart primary">

<span>
<a href="<?= $_product->getProductUrl() ?>">
<?= __('SHOP NOW') ?>
</a>
</span>

</button>

</form>

<?php else: ?>

<?php if ($_product->isAvailable()): ?>
<div class="stock available"><span><?= __('In stock') ?></span></div>
<?php else: ?>
<div class="stock unavailable"><span><?= __('Out of stock') ?></span></div>
<?php endif; ?>

<?php endif; ?>

</div>

<div data-role="add-to-links"
class="actions-secondary"
<?= strpos($pos, $viewMode . '-secondary') !== false ? $position : '' ?>>

<?php if ($addToBlock = $block->getChildBlock('addto')): ?>
<?= $addToBlock->setProduct($_product)->getChildHtml() ?>
<?php endif; ?>

</div>

</div>

<?php if ($showDescription): ?>

<div class="product description product-item-description">

<?= $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>

<a href="<?= $_product->getProductUrl() ?>"
title="<?= $_productNameStripped ?>"
class="action more">

<?= __('Learn More') ?>

</a>

</div>

<?php endif; ?>

</div>

</div>

</div>

</li>

<?php endforeach; ?>

</ol>
</div>

<?= $block->getToolbarHtml() ?>

<?php endif; ?>

</div>