<div class="bb w-full">
    <div class="flex items-center justify-between py-3 px-4 md:px-6">

        <!-- Logo -->
        <div class="flex-shrink-0">
            <?= $block->getChildHtml('logo') ?>
        </div>

        <!-- Menu -->
        <div class="hidden md:block flex-grow text-center">
            <?= $block->getChildHtml('catalog.topnav') ?>
        </div>

        <!-- Cart -->
        <div class="flex-shrink-0">
            <?= $block->getChildHtml('minicart') ?>
        </div>

    </div>
</div>