<div class="w-screen relative left-1/2 right-1/2 -ml-[50vw] -mr-[50vw]">
<div class="grid grid-cols-3 items-center py-3 px-6">
    <div class="bg-white">
        <?= $block->getChildHtml('logo') ?>
    </div>

    <div class="text-center bg-white text-black">
        <?= $block->getChildHtml('catalog.topnav') ?>
    </div>

    <div class="text-right">
        <?= $block->getChildHtml('minicart') ?>
    </div>
</div>
</div>