<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
<div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?= /* @escapeNotVerified */ $title ?>
    </h1>
 
    <div class="mt-2">

    <?php
    $product = $block->getLayout()
        ->getBlock('product.info')
        ->getProduct();
    ?>

    <?php
        $helper = $this->helper(\BeautyBop\Base\Helper\Data::class);
        $rating = $helper->getProductRating($product);
    ?>
        <div class="flex items-center gap-2 mb-2">
            <span class="text-yellow-500 text-lg"><?= $rating['stars']; ?></span>
            <span class="font-semibold"><?= $rating['score']; ?> out of 5</span>
            <span class="text-gray-500">(<?= $rating['count']; ?> reviews)</span>
        </div>
    </div>
   
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
