<div class="bb-checkout-header">

<div class="bb-checkout-header__inner">

    <div class="bb-checkout-logo">
        <a class="logo xl:w-[270px] w-[100%] max-w-[158px] m-0" href="https://staging.beautybop.co.uk/" title="">
            <img src="https://staging.beautybop.co.uk/media/logo/stores/1/logo-new-white.png" title="" alt="" width="170">
        </a>
    </div>

    <div class="bb-checkout-title">

        <span class="bb-lock-icon">
            <img
                src="<?= $block->getViewFileUrl('images/icons/majesticons_lock.svg') ?>"
                alt=""
            >
        </span>

        <div class="bb-checkout-copy">

            <h2 class="font-semibold text-[23px]">Secure Checkout</h2>

            <p>You're only a few steps away from your order.</p>

        </div>

    </div>


    <div class="checkout-badge">
        <h2>✓ Guest Checkout Available</h2>
        <p>No account required</p>
    
    </div>

   
</div>

</div>


