<?php

$dataPostParam = '';
$custom_label = __("Login"); // Added custom text
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
    $custom_label = $block->getLabel();
}
?>
<li class="authorization-link" data-label="<?= $block->escapeHtmlAttr(__('or')) ?>">
    <a <?=  $block->getLinkAttributes() ?><?= $dataPostParam ?>>
        <?= $block->escapeHtml($custom_label) ?>
    </a>
</li>
