<?php

$order = $block->getOrder();

?>

<tr>
    <td colspan="3" style="padding-top:30px;">

        <table
            width="100%"
            cellpadding="0"
            cellspacing="0"
            style="
                border:1px solid #ececec;
                border-radius:8px;
                background:#ffffff;
            ">
        
        <tr>

        <td
        colspan="2"
        style="
            padding:20px;
            font-size:20px;
            font-weight:bold;
        ">

        Order Summary

        </td>

        </tr>
            
        <tr>

            <td style="padding:12px 20px;">
                Subtotal
            </td>

            <td
                align="right"
                style="padding:12px 20px;">

                <?= $order->formatPrice($order->getSubtotal()) ?>

            </td>

        </tr>

        <tr>

            <td style="padding:12px 20px;">
            Shipping
            </td>

            <td
                align="right"
                style="padding:12px 20px;">

            <?= $order->formatPrice($order->getShippingAmount()) ?>

            </td>

        </tr>

        <tr>

            <td colspan="2">

                <hr
                style="
                border:none;
                border-top:1px solid #ececec;
                margin:0;
                ">

            </td>

        </tr>

        <tr>

            <td
            style="
            padding:20px;
            font-size:20px;
            font-weight:bold;
            ">

            Grand Total

            </td>

            <td
            align="right"
            style="
            padding:20px;
            font-size:24px;
            font-weight:bold;
            ">

            <?= $order->formatPrice($order->getGrandTotal()) ?>

            </td>

        </tr>