
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $objectManager->create(\Magento\Catalog\Model\ResourceModel\Product\Collection::class);

$productCollection->addAttributeToSelect('*')
->addAttributeToFilter('status', 1)
->addAttributeToFilter('visibility', 4)
->setPageSize(8);

?>

<?php
$imageHelper = \Magento\Framework\App\ObjectManager::getInstance()
->get(\Magento\Catalog\Helper\Image::class);
?>


<!-- FEATURED PRODUCTS -->
    <section class="py-16">

        <div class="bb-categories__intro">
            <?= $this->getLayout()
                    ->createBlock(\Magento\Cms\Block\Block::class)
                    ->setBlockId('bb-home-featured-intro')
                    ->toHtml(); ?>
        </div>

       <div class="grid grid-cols-2 md:grid-cols-4 gap-6">

        <?php foreach ($productCollection as $product): ?>

           <div class="group border bg-white p-5 transition duration-300 hover:shadow-xl hover:-translate-y-1">

            <a href="<?= $product->getProductUrl(); ?>" class="block overflow-hidden">
                <img 
                    src="<?= $imageHelper->init($product, 'product_small_image')->getUrl(); ?>" 
                    alt="<?= $product->getName(); ?>"
                    class="h-52 w-full object-contain mx-auto transition duration-300 group-hover:scale-105"
                />
            </a>

            <h3 class="mt-3 text-2xl text-gray-700 leading-tight min-h-[44px]">
                <?= $product->getName(); ?>
            </h3>

            <div class="mt-3 border-t pt-3"></div>

            <div class="text-2xl font-semibold text-black">
                £<?= number_format($product->getFinalPrice(), 2); ?>
            </div>

            <form action="<?= $block->getUrl('checkout/cart/add'); ?>" method="post" class="mt-3">
                <input type="hidden" name="product" value="<?= $product->getId(); ?>" />
                <input type="hidden" name="form_key" value="<?= $block->getFormKey(); ?>" />

                <button 
                    type="submit"
                    class="w-full border border-black py-2 text-sm font-medium tracking-wide transition duration-300 hover:bg-black hover:text-white"
                >
                    Add to Cart
                </button>
            </form>

        </div>

        <?php endforeach; ?>

        </div>
    </section>