<section class="bb-home-hero" style="background-repeat: no-repeat;">

    <div class="bb-home-hero__content">

        <div class="bb-home-hero__left">

            <span class="bb-home-hero__eyebrow text-[#C9A227] font-semibold">
                DESIGNER FRAGRANCES
            </span>

            <h1 class="text-[68px] w-[693] h-[147]">
                Luxury Fragrances
                For Men & Women
            </h1>

            <p class="max-w-[520px] mt-[24px] text-[24px] font-[400px] leading-1">
                Discover genuine designer perfumes
                and aftershaves from leading brands
                including Hugo Boss, Prada and more.
            </p>

            <div class="bb-home-hero__buttons">

                <a href="/mens-fragrance"
                   class="btn-primary bg-[#111827] rounded-[12px] text-white text-[12px] w-[220px] h-[46px] z-[2]  text-center py-4 ">
                    Shop Men's Fragrances
                </a>

                <a href="/womens-fragrance"
                   class="btn-secondary z-[2] text-center py-4 border-black border-solid border-[1px] w-[220px] h-[46px] rounded-[12px] hover:bg-[#111827]">
                    Shop Women's Fragrances
                </a>

            </div>

        </div>

        <div class="bb-home-hero__right flex">

            <img
                src="/media/home/boss-scent.png"
                alt="Boss The Scent"
                class="bottle bottle-1"
            >

            <img
                src="/media/home/boss-bottled.png"
                alt="Hugo Man"
                class="bottle bottle-2"
            >

        </div>

    </div>

</section>