 <!-- BRAND GRID -->
    <section class="py-14">
        <h2 class="text-4xl font-bold mb-6 text-center">
            Shop by Brand
        </h2>

        <div class="grid grid-cols-2 md:grid-cols-4 gap-6 text-center">
            <a href="/brands/hugo-boss-fragrance.html">Hugo Boss</a>
            <a href="/brands/calvin-klein-fragrance.html">Calvin Klein</a>
            <a href="/brands/prada-fragrance.html">Prada</a>
            <a href="/brands/jean-paul-gaultier-fragrance.html">JPG</a>
        </div>
    </section>