<section class="bb-trust-bar bb-trust-desktop">
  
    <div class="bb-trust-bar__container">

        <div class="bb-trust-item">
            <div class="bb-trust-icon">
                <img src="<?= $block->getViewFileUrl('images/icons/shield.svg') ?>" alt="">
            </div>
            <div class="bb-trust-content">
                <h3>100% Authentic</h3>
                <p>Genuine designer products</p>
            </div>
        </div>

        <div class="bb-trust-item">
            <div class="bb-trust-icon">
                <img src="<?= $block->getViewFileUrl('images/icons/truck.svg') ?>" alt="">
            </div>
            <div class="bb-trust-content">
                <h3>Fast UK Delivery</h3>
                <p>Easy Returns</p>
            </div>
        </div>

        <div class="bb-trust-item">
            <div class="bb-trust-icon">
                <img src="<?= $block->getViewFileUrl('images/icons/lock.svg') ?>" alt="">
            </div>
            <div class="bb-trust-content">
                <h3>Secure Payment</h3>
                <p>Safe &amp; encrypted payments</p>
            </div>
        </div>

        <div class="bb-trust-item">
            <div class="bb-trust-icon">
                <img src="<?= $block->getViewFileUrl('images/icons/package.svg') ?>" alt="">
            </div>
            <div class="bb-trust-content">
                <h3>Fast Dispatch</h3>
                <p>Quick UK delivery <br> service</p>
            </div>
        </div>

        <div class="bb-trust-item">
            <div class="bb-trust-icon">
                <img src="<?= $block->getViewFileUrl('images/icons/established-since.svg') ?>" alt="">
            </div>
            <div class="bb-trust-content">
                <h3>12+ Years Trading</h3>
                <p>Trusted online since 2014</p>
            </div>
        </div>

    </div>

</section>


<!--<div class="swiper bb-trust-mobile">

    <div class="swiper-wrapper">

        <div class="swiper-slide">
            <div class="bb-trust-item">
                <div class="bb-trust-icon">
                    <img src="<?= $block->getViewFileUrl('images/icons/shield.svg') ?>" alt="">
                </div>

                <div class="bb-trust-content">
                    <h3>Genuine Products</h3>
                </div>
            </div>
        </div>

        <div class="swiper-slide">
            <div class="bb-trust-item">
                <div class="bb-trust-icon">
                    <img src="<?= $block->getViewFileUrl('images/icons/truck.svg') ?>" alt="">
                </div>

                <div class="bb-trust-content">
                    <h3>Free UK Delivery</h3>
                </div>
            </div>
        </div>

        <div class="swiper-slide">
            <div class="bb-trust-item">
                <div class="bb-trust-icon">
                    <img src="<?= $block->getViewFileUrl('images/icons/lock.svg') ?>" alt="">
                </div>

                <div class="bb-trust-content">
                    <h3>Secure Checkout</h3>
                </div>
            </div>
        </div>

        <div class="swiper-slide">
            <div class="bb-trust-item">
                <div class="bb-trust-icon">
                    <img src="<?= $block->getViewFileUrl('images/icons/package.svg') ?>" alt="">
                </div>

                <div class="bb-trust-content">
                    <h3>Fast Dispatch</h3>
                </div>
            </div>
        </div>

        <div class="swiper-slide">
            <div class="bb-trust-item">
                <div class="bb-trust-icon">
                    <img src="<?= $block->getViewFileUrl('images/icons/established-since.svg') ?>" alt="">
                </div>

                <div class="bb-trust-content">
                    <h3>12+ Years Trading</h3>
                </div>
            </div>
        </div>

    </div>


</div>-->



    



